# Generated by Django 4.2.11 on 2024-03-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='question_text',
            new_name='task_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
