apiVersion: v1
kind: Service
metadata:
  name: todobasa
  namespace: default
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: back-app # сервиc будет искать ЭТИ поды! СМ. создание подов в deploy, template
  ports:
    - name: app-listener
      protocol: TCP
      port: 8000  # on load balancer
      targetPort: 8000 # on POD
  type: ClusterIP